### ISSUE TITLE
Bus Factor

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/Meta#46]
This is a list of issues I would like to solve in Wasabi before I get hit by a bus. This is not only a list that only I can do, rather this is a list that consists of long term decisions and fixes those can make the job of the developers coming after me easier.

- [ ] Bitcoin Core Integration: This is not a work that can be justified by any kind of business logic, however it is utmost important for the future of Bitcoin, I feel like if I don't push it myself, it will not be done.
- [x] Password Bruteforcer - It'd lower the number of "I lost my password" support tickets: https://github.com/zkSNACKs/WalletWasabi/issues/1035
- [x]  Fix our RBF policy - The way we accept transactions to the mempool is not perfect, this'd lower the chance of future surprises: https://github.com/zkSNACKs/WalletWasabi/issues/474
- [x]  Mempool filters? - A way to recognize unconfirmed transactions after wallet start would lower the number of support requests regarding this topic.
- [ ]  Incorporate WindowsInstaller project into the Packager project - This would make the packaging process simpler. https://github.com/zkSNACKs/WalletWasabi/issues/691
- [ ]  Cache some stuff so loading the wallet would be faster - Valuable development time is spent waiting for wallet loading: https://github.com/zkSNACKs/WalletWasabi/issues/444
- [ ]  Speed up wallet by disabling address reuse - Same logic as above: https://github.com/zkSNACKs/WalletWasabi/issues/1190
- [ ]  Toast Notifications - So the dev won't have to keep finding places on the UI for error showing: https://github.com/zkSNACKs/WalletWasabi/issues/845
- [ ]  Tidy XAML Code: https://github.com/zkSNACKs/WalletWasabi/issues/1056
- [x]  Dangerous Clearnet feature - Another tool in our toolbox to handle support requests when there are Tor issues: https://github.com/zkSNACKs/WalletWasabi/issues/996
- [ ]  Figure out proper sync mechnaism for terms, privacy and legal documents with website: https://github.com/zkSNACKs/WalletWasabi/issues/596

**Comment by nopara73** [comment]
Superseded by https://github.com/zkSNACKs/Meta/issues/68
